apiVersion: v1
kind: Service
metadata:
  name: static-content-service
  namespace: social-ai-profile
spec:
  selector:
    app: static-content
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80