version: "3"

services:
  fastapi-auth-api:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: auth.Dockerfile
    env_file:
      - .env
    networks:
      - social-ai-portrait
    expose:
      - "8000"
    depends_on:
      redis:
        condition: service_healthy


  bot:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: bot.Dockerfile
    env_file:
      - .env
    networks:
      - social-ai-portrait
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    privileged: true
    networks:
      - social-ai-portrait
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5

  nginx:
    image: nginx:latest
    restart: always
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./www/:/var/www/
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      fastapi-auth-api:
        condition: service_started
      bot:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - social-ai-portrait


networks:
  social-ai-portrait:
