apiVersion: "acid.zalan.do/v1"
kind: "postgresql"

metadata:
  name: "sap-pg-cluster"
  namespace: social-ai-profile
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 1
  enableMasterLoadBalancer: true
  enableReplicaLoadBalancer: true
  enableConnectionPooler: true
  enableMasterPoolerLoadBalancer: true
  volume:
    size: "10Gi"
  users:
    app:
      - superuser
      - createdb
  databases:
    sap_database: app
  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi