apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: auth-api
  labels:
    app: auth-api
  namespace: social-ai-profile
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.auth
  output:
    to:
      kind: ImageStreamTag
      name: auth-api:latest