version: '3'

services:
  test-app:
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    env_file:
      - .env
    networks:
      - test_apps
    depends_on:
      redis:
        condition: service_healthy
    #entrypoint: ${APP_HOME}/test_apps/end_to_end/entrypoint.sh
    volumes:
      - ./../../auth_api/src:/${APP_HOME}/auth_api/src
      - ./../../auth_app:/${APP_HOME}/auth_app
      - ./../../db:/${APP_HOME}/db
      - ./../../project_settings:/${APP_HOME}/project_settings
      - ./../../helpers:/${APP_HOME}/helpers
      - ./../../test_apps:/${APP_HOME}/test_apps

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    privileged: true
    networks:
      - test_apps
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5


networks:
  test_apps:
