apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-sa
  namespace: social-ai-profile

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: build-role
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments", "pods", "services", "secrets", "configmaps"]
  verbs: [ "create", "get", "list", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: build-binding
subjects:
- kind: ServiceAccount
  name: build-sa
  namespace: social-ai-profile
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: build-role
