{
 "title": "App_dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU: percentage of limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!~\".*prometheus.*|.*cadvisor.*|.*grafana.*\", image!=\"\"}[5m])) by (name) /\nsum(100000/container_spec_cpu_period{name!~\".*prometheus.*|.*cadvisor.*|.*grafana.*\", image!=\"\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current memory usage in bytes, including all memory regardless of when it was accessed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"fastapi-auth-api\"} or \ncontainer_memory_usage_bytes{name=\"bot\"}  or\ncontainer_memory_usage_bytes{name=\"nginx\"}  or\ncontainer_memory_usage_bytes{name=\"redis\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "timeseries",
   "description": "Total number of requests",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total",
     "legendFormat": "{{handler}} - {{method}} - {{status}}"
    }
   ]
  }
 ]
}