apiVersion: v1
kind: ServiceAccount
metadata:
  name: ansible-operator-service-account
  namespace: social-ai-profile
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ansible-operator-reader
rules:
- apiGroups: ["ansibleoperator.com"]
  resources: ["ansibleoperators"]
  verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ansible-operator-binding
subjects:
- kind: ServiceAccount
  name: ansible-operator-service-account
  namespace: social-ai-profile
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io