apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  namespace: social-ai-profile
  labels:
    app: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      serviceAccountName: build-sa
      containers:
      - name: auth-api
        image: auth-api
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secrets
        volumeMounts:
          - name: keys-secrets
            mountPath: "/app/keys"
      volumes:
        - name: keys-secrets
          secret:
            secretName: keys-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
  namespace: social-ai-profile
spec:
  selector:
    app: auth-api
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
