name: Test Auth FastAPI App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Set environment variables from secrets and create .env file
      run: |
          mkdir -p ./test_apps/end_to_end/keys
          echo "${{ secrets.ENV_FILE }}" > ./test_apps/end_to_end/.env
          echo "${{ secrets.PRIVATE_KEY }}" > ./test_apps/end_to_end/keys/private_key.pem
          echo "${{ secrets.PUBLIC_KEY }}" > ./test_apps/end_to_end/keys/public_key.pem
          ls -al

    - name: Run docker-compose
      uses: hoverkraft-tech/compose-action@v2.0.1
      with:
        compose-file: "./test_apps/end_to_end/docker-compose.yml"
    - name: Execute tests in the running services
      run: |
        docker start -a end_to_end-test-app-1